/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansmac
 */
public class ForgotPasswordFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordFrame2
     */
    public ForgotPasswordFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        forgotPassword2BackButton = new javax.swing.JButton();
        forgotPassword2SecurityQuestionLabel = new javax.swing.JLabel();
        forgotPassword2SecurityQuestionGoesHereLabel = new javax.swing.JLabel();
        forgotPassword2AnswerToSecurityQuestionField = new javax.swing.JTextField();
        forgotPassword2OkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        forgotPassword2BackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        forgotPassword2BackButton.setText("Back");
        forgotPassword2BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassword2BackButtonMouseClicked(evt);
            }
        });

        forgotPassword2SecurityQuestionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        forgotPassword2SecurityQuestionLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword2SecurityQuestionLabel.setText("Security Question:");

        forgotPassword2SecurityQuestionGoesHereLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        forgotPassword2SecurityQuestionGoesHereLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword2SecurityQuestionGoesHereLabel.setText("Security Question Goes Here...");

        forgotPassword2AnswerToSecurityQuestionField.setText("Enter Answer to Security Question...");

        forgotPassword2OkButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        forgotPassword2OkButton.setText("Ok");
        forgotPassword2OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassword2OkButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(forgotPassword2BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgotPassword2SecurityQuestionLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(forgotPassword2SecurityQuestionGoesHereLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(forgotPassword2AnswerToSecurityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(193, 193, 193))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(forgotPassword2OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(forgotPassword2BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(forgotPassword2SecurityQuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(forgotPassword2SecurityQuestionGoesHereLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(forgotPassword2AnswerToSecurityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(forgotPassword2OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPassword2BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassword2BackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        ForgotPasswordFrame forgotPasswordPage = new ForgotPasswordFrame();
        forgotPasswordPage.setVisible(true);
    }//GEN-LAST:event_forgotPassword2BackButtonMouseClicked

    private void forgotPassword2OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassword2OkButtonMouseClicked
        // if security question answer in DB == to answer input, then load success page
//        this.remove(this);
//        this.setVisible(false);
//        ForgotPasswordSuccessFrame successPage = new ForgotPasswordSuccessFrame();
//        successPage.setVisible(true);


        // else load failure page
//        this.remove(this);
//        this.setVisible(false);
//        ForgotPasswordFailureFrame failurePage = new ForgotPasswordFailureFrame();
//        failurePage.setVisible(true);
    }//GEN-LAST:event_forgotPassword2OkButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ForgotPasswordFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ForgotPasswordFrame2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField forgotPassword2AnswerToSecurityQuestionField;
    private javax.swing.JButton forgotPassword2BackButton;
    private javax.swing.JButton forgotPassword2OkButton;
    private javax.swing.JLabel forgotPassword2SecurityQuestionGoesHereLabel;
    private javax.swing.JLabel forgotPassword2SecurityQuestionLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
