/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ryansmac
 */
public class InputHoursFrame extends javax.swing.JFrame {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form InputHoursFrame
     */
    public InputHoursFrame(User user, Connection connection) {
        this.user = user;
        this.connection = connection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputHoursBackButton = new javax.swing.JButton();
        inputHoursOTHoursLabel = new javax.swing.JLabel();
        inputHoursConfirmButton = new javax.swing.JButton();
        inputHoursHoursLabel = new javax.swing.JLabel();
        inputHoursHoursMenu = new javax.swing.JComboBox<>();
        inputHoursOTHoursMenu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        inputHoursBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        inputHoursBackButton.setText("Back");
        inputHoursBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputHoursBackButtonMouseClicked(evt);
            }
        });

        inputHoursOTHoursLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        inputHoursOTHoursLabel.setForeground(new java.awt.Color(255, 255, 255));
        inputHoursOTHoursLabel.setText("OT Hours Worked this Week (round to nearest hour):");

        inputHoursConfirmButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        inputHoursConfirmButton.setText("Confirm");
        inputHoursConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputHoursConfirmButtonMouseClicked(evt);
            }
        });

        inputHoursHoursLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        inputHoursHoursLabel.setForeground(new java.awt.Color(255, 255, 255));
        inputHoursHoursLabel.setText("Hours Worked this Week (round to nearest hour):");

        inputHoursHoursMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enter Number of Hours...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        inputHoursOTHoursMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enter Number of OT Hours...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputHoursBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(inputHoursConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputHoursOTHoursMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHoursHoursMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHoursHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHoursOTHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inputHoursBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(inputHoursHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputHoursHoursMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(inputHoursOTHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputHoursOTHoursMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(inputHoursConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputHoursBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputHoursBackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        UserDashBoardFrame userDashBoardpage = new UserDashBoardFrame(user, connection);
        userDashBoardpage.setVisible(true);
    }//GEN-LAST:event_inputHoursBackButtonMouseClicked

    private void inputHoursConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputHoursConfirmButtonMouseClicked
        // queries DB for employee hourly rate
        // then takes hourly rate, multiplies by hours worked
        // then takes hourly rate * 1.5 and multiplies by OT hours worked
        // then adds two values together and saves paycheck value owed to DB
        // then loads success page where admin will need to confirm hours are correct
        
        try {
            String psQuery = 
                    "SELECT wage FROM employees " +
                    "WHERE employeeid = ?";
            
            PreparedStatement ps = connection.prepareStatement(psQuery);
            
            System.out.println("Employee ID: " + user.getEmployeeID());
            ps.setInt(1, user.getEmployeeID());
            ResultSet employeeInfo = ps.executeQuery();
            
            employeeInfo.next();
            int hours = Integer.parseInt(inputHoursHoursMenu.getSelectedItem().toString());
            int ot_hours = Integer.parseInt(inputHoursOTHoursMenu.getSelectedItem().toString());
            float wage = employeeInfo.getFloat("wage");
            
            float pay = wage * hours + (wage * 1.5f * ot_hours);
            
            System.out.println("Pay is: " + pay);
            
            String psInsertQuery = 
                    "INSERT INTO employee_stubs (employeeid, paydate, payamount, hours, ot_hours, approval) " +
                    "VALUES (?, ?, ?, ?, ?, 0)";
            
            ps = connection.prepareStatement(psInsertQuery);
            
            ps.setInt(1, user.getEmployeeID());
            
            String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            System.out.println("Date: " + date);
            ps.setString(2, date);
            
            ps.setFloat(3, pay);
            ps.setInt(4, hours);
            ps.setInt(5, ot_hours);
            
            ps.executeUpdate();
        }
        catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
        this.remove(this);
        this.setVisible(false);
        InputHoursSuccessFrame inputHoursSuccessPage = new InputHoursSuccessFrame(user, connection);
        inputHoursSuccessPage.setVisible(true);
    }//GEN-LAST:event_inputHoursConfirmButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InputHoursFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InputHoursFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InputHoursFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InputHoursFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InputHoursFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputHoursBackButton;
    private javax.swing.JButton inputHoursConfirmButton;
    private javax.swing.JLabel inputHoursHoursLabel;
    private javax.swing.JComboBox<String> inputHoursHoursMenu;
    private javax.swing.JLabel inputHoursOTHoursLabel;
    private javax.swing.JComboBox<String> inputHoursOTHoursMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
