
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ryansmac
 */
public class LoginFrame extends javax.swing.JFrame {
    private Connection connection;
    private PasswordManager pwdmg;
    private User user;
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        if (!pwdmg.initDB("root", "sesame123")) {
            System.err.println("PWD MG FAILED");
            System.exit(1);
        }
        connection = pwdmg.connection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        loginUsernameLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginLoginButton = new javax.swing.JButton();
        loginForgotPasswordButton = new javax.swing.JButton();
        loginSignUpButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        loginUsernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        loginUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernameLabel.setText("Username:");

        loginPasswordField.setSize(new java.awt.Dimension(80, 26));

        loginPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Password:");

        loginLoginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginLoginButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        loginLoginButton.setText("Login");
        loginLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLoginButtonMouseClicked(evt);
            }
        });

        loginForgotPasswordButton.setBackground(new java.awt.Color(255, 255, 255));
        loginForgotPasswordButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        loginForgotPasswordButton.setText("Forgot Password");
        loginForgotPasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginForgotPasswordButtonMouseClicked(evt);
            }
        });

        loginSignUpButton.setBackground(new java.awt.Color(255, 255, 255));
        loginSignUpButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        loginSignUpButton.setText("Sign Up");
        loginSignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginSignUpButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginSignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginForgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(loginUsernameField))
                    .addComponent(loginLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(loginLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(loginForgotPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(loginSignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginSignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginSignUpButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        SignUpFrame signUpPage = new SignUpFrame();
//        signUpPage.add(jPanel1);
        signUpPage.setVisible(true);
        
    }//GEN-LAST:event_loginSignUpButtonMouseClicked

    private void loginForgotPasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginForgotPasswordButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        ForgotPasswordFrame forgotPasswordPage = new ForgotPasswordFrame();
        forgotPasswordPage.setVisible(true);
    }//GEN-LAST:event_loginForgotPasswordButtonMouseClicked

    private void loginLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLoginButtonMouseClicked
        String username = loginUsernameField.getText();
        String pass = new String(loginPasswordField.getPassword());
        String thePassTest = new String(pass);
        try {   
                String psQuery = "SELECT userid, username, role FROM users WHERE username = ?";
                PreparedStatement ps = connection.prepareStatement(psQuery);
                ps.setString(1, username);
                
                ResultSet userInfo = ps.executeQuery();
                
                userInfo.next();
                
                psQuery = "SELECT employeeid FROM employees WHERE userid = ?";
                ps = connection.prepareStatement(psQuery);
                ps.setInt(1, userInfo.getInt(1));
                
                ResultSet employeeInfo = ps.executeQuery();
                
                employeeInfo.next();
                
                user = new User(
                        userInfo.getInt(1), employeeInfo.getInt(1),
                        userInfo.getString(2), userInfo.getInt(3)
                );
                
                boolean correctPassword = pwdmg.checkPassword(username, pass);
                
                if (correctPassword && user.getRole() == 0) {
                    // user
                    this.remove(this);
                    this.setVisible(false);
                    UserDashBoardFrame userDashBoardPage = new UserDashBoardFrame(user, connection);
                    userDashBoardPage.setVisible(true);
                }

                if (correctPassword && user.getRole() == 1) {
                    // admin
                    this.remove(this);
                    this.setVisible(false);
                    AdminDashBoardFrame adminDashBoardPage = new AdminDashBoardFrame(user, connection);
                    adminDashBoardPage.setVisible(true);
                }
        }
        catch (Exception e) {

        }
        
    }//GEN-LAST:event_loginLoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginForgotPasswordButton;
    private javax.swing.JButton loginLoginButton;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JButton loginSignUpButton;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JLabel loginUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
