/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;

/**
 *
 * @author ryansmac
 */
public class RemoveEmployeeFrame extends javax.swing.JFrame {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form RemoveEmployeeFrame
     */
    public RemoveEmployeeFrame(User user, Connection connection) {
        this.connection = connection;
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        removeEmployeeBackButton = new javax.swing.JButton();
        removeEmployeeEmployeeListLabel = new javax.swing.JLabel();
        removeEmployeeSelectEmployeeMenu = new javax.swing.JComboBox<>();
        removeEmployeeRemoveUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        removeEmployeeBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        removeEmployeeBackButton.setText("Back");
        removeEmployeeBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeEmployeeBackButtonMouseClicked(evt);
            }
        });

        removeEmployeeEmployeeListLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        removeEmployeeEmployeeListLabel.setForeground(new java.awt.Color(255, 255, 255));
        removeEmployeeEmployeeListLabel.setText("Employee List:");

        removeEmployeeSelectEmployeeMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee..." }));

        try {
            String psQuery = 
            "SELECT employeeid, firstname, lastname, wage FROM employees";

            PreparedStatement ps = connection.prepareStatement(psQuery);

            ResultSet employeeInfo = ps.executeQuery();

            for (int i = 0; employeeInfo.next(); i++) {
                String employee = new String(employeeInfo.getInt("employeeid") + 
                        ": " + employeeInfo.getString("lastname") + ", " + employeeInfo.getString("firstname"));
                
                removeEmployeeSelectEmployeeMenu.addItem(employee);
            }
               
        }
        catch (Exception e) {
                
                }
        
        removeEmployeeRemoveUserButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        removeEmployeeRemoveUserButton.setText("Remove Selected User");
        removeEmployeeRemoveUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeEmployeeRemoveUserButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeEmployeeBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(removeEmployeeEmployeeListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(removeEmployeeSelectEmployeeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(removeEmployeeRemoveUserButton)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(removeEmployeeBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(removeEmployeeEmployeeListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeEmployeeSelectEmployeeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(removeEmployeeRemoveUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeEmployeeBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEmployeeBackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        AdminDashBoardFrame adminDashBoardpage = new AdminDashBoardFrame(user, connection);
        adminDashBoardpage.setVisible(true);
    }//GEN-LAST:event_removeEmployeeBackButtonMouseClicked

    private void removeEmployeeRemoveUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEmployeeRemoveUserButtonMouseClicked
        // will have to query DB to populate menu picker with employee names and then when one chosen,
        // will have a confirm dialog box pop up
        // load confirm page
        try {
            String psQuery =
                    "SELECT userid FROM employees WHERE employeeid = ?";
            
            PreparedStatement ps = connection.prepareStatement(psQuery);
            
            String employee = removeEmployeeSelectEmployeeMenu.getSelectedItem().toString();
            System.out.println(employee);
            String[] employeeData = employee.split(":");
//            for (int i = 0; i < employeeData.length; i++) {
//                System.out.println(employeeData[i]);
//            }
            int employeeID = Integer.parseInt(employeeData[0]);
            
            System.out.println(employeeID);
            
            ps.setInt(1, employeeID);
            
            ResultSet userInfo = ps.executeQuery();
            userInfo.next();
            
            int userID = userInfo.getInt("userid");
            
            System.out.println("USER ID IS : " + userID);
            
            this.remove(this);
            this.setVisible(false);
            ConfirmRemoveFrame confirmRemovalPage = new ConfirmRemoveFrame(user, userID, employeeID, connection);
            confirmRemovalPage.setVisible(true);
        }   
        catch (Exception e) {
            
        }
    }//GEN-LAST:event_removeEmployeeRemoveUserButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RemoveEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RemoveEmployeeFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removeEmployeeBackButton;
    private javax.swing.JLabel removeEmployeeEmployeeListLabel;
    private javax.swing.JButton removeEmployeeRemoveUserButton;
    private javax.swing.JComboBox<String> removeEmployeeSelectEmployeeMenu;
    // End of variables declaration//GEN-END:variables
}
