/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;

/**
 *
 * @author ryansmac
 */
public class UserDashBoardFrame extends javax.swing.JFrame {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form UserDashBoardFrame
     */
    public UserDashBoardFrame(User user, Connection connection) {
        this.user = user;
        this.connection = connection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userDashBoardYTDLabel = new javax.swing.JLabel();
        userDashBoardChangePersonalInfoButton = new javax.swing.JButton();
        userDashBoardViewPaystubsButton = new javax.swing.JButton();
        userDashBoardInputHoursButton = new javax.swing.JButton();
        userDashBoardLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        userDashBoardYTDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        userDashBoardYTDLabel.setForeground(new java.awt.Color(255, 255, 255));
        userDashBoardYTDLabel.setText("YTD Gross Earnings: $0.00");

        userDashBoardChangePersonalInfoButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        userDashBoardChangePersonalInfoButton.setText("Change Personal Info");
        userDashBoardChangePersonalInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDashBoardChangePersonalInfoButtonMouseClicked(evt);
            }
        });

        userDashBoardViewPaystubsButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        userDashBoardViewPaystubsButton.setText("View Paystubs");
        userDashBoardViewPaystubsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDashBoardViewPaystubsButtonMouseClicked(evt);
            }
        });

        userDashBoardInputHoursButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        userDashBoardInputHoursButton.setText("Input Hours");
        userDashBoardInputHoursButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDashBoardInputHoursButtonMouseClicked(evt);
            }
        });

        userDashBoardLogoutButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        userDashBoardLogoutButton.setText("Logout");
        userDashBoardLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDashBoardLogoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDashBoardInputHoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDashBoardViewPaystubsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDashBoardChangePersonalInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDashBoardYTDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(userDashBoardLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userDashBoardYTDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(userDashBoardChangePersonalInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(userDashBoardViewPaystubsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(userDashBoardInputHoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(userDashBoardLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userDashBoardLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDashBoardLogoutButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        LoginFrame loginPage = new LoginFrame();
        loginPage.setVisible(true);
    }//GEN-LAST:event_userDashBoardLogoutButtonMouseClicked

    private void userDashBoardChangePersonalInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDashBoardChangePersonalInfoButtonMouseClicked
        // will need to load in from DB all current fields in this form
        this.remove(this);
        this.setVisible(false);
        ChangePersonalInfoFrame changePersonalInfoPage = new ChangePersonalInfoFrame(user, connection);
        changePersonalInfoPage.setVisible(true);
    }//GEN-LAST:event_userDashBoardChangePersonalInfoButtonMouseClicked

    private void userDashBoardViewPaystubsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDashBoardViewPaystubsButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        ViewPaystubsFrame viewPaystubsPage = new ViewPaystubsFrame(user, connection);
        viewPaystubsPage.setVisible(true);
    }//GEN-LAST:event_userDashBoardViewPaystubsButtonMouseClicked

    private void userDashBoardInputHoursButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDashBoardInputHoursButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        InputHoursFrame inputHoursPage = new InputHoursFrame(user, connection);
        inputHoursPage.setVisible(true);
    }//GEN-LAST:event_userDashBoardInputHoursButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserDashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserDashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserDashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserDashBoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserDashBoardFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton userDashBoardChangePersonalInfoButton;
    private javax.swing.JButton userDashBoardInputHoursButton;
    private javax.swing.JButton userDashBoardLogoutButton;
    private javax.swing.JButton userDashBoardViewPaystubsButton;
    private javax.swing.JLabel userDashBoardYTDLabel;
    // End of variables declaration//GEN-END:variables
}
