/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.*;

/**
 *
 * @author ryansmac
 */
public class ViewEmployeeYTDPaymentsFrame extends javax.swing.JFrame implements WindowListener {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form ViewEmployeeYTDPaymentsFrame
     */
    public ViewEmployeeYTDPaymentsFrame(User user, Connection connection) {
        this.connection = connection;
        this.user = user;
        initComponents();
    }

    private void fillTable() {
        try {
            String psQuery = 
                    "SELECT firstname, lastname, ytd_earned FROM employees";
            
            PreparedStatement ps = connection.prepareStatement(psQuery);
            
            ResultSet employeeInfo = ps.executeQuery();
            
            for (int i = 0; employeeInfo.next(); i++) {
                viewEmployeeYTDPaymentsTable.setValueAt(
                        new String(
                                employeeInfo.getString("lastname") + ", " + employeeInfo.getString("firstname")
                                ),
                        i, 0);
                viewEmployeeYTDPaymentsTable.setValueAt(new String("$" + employeeInfo.getFloat("ytd_earned")), i, 1);
            }
        }
        catch (Exception e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        addWindowListener(this);
        
        jPanel1 = new javax.swing.JPanel();
        viewEmployeeYTDPaymentsBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewEmployeeYTDPaymentsTable = new javax.swing.JTable();
        viewEmployeeYTDPaymentsEmployeeNameLabel = new javax.swing.JLabel();
        viewEmployeeYTDPaymentsYTDLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        viewEmployeeYTDPaymentsBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewEmployeeYTDPaymentsBackButton.setText("Back");
        viewEmployeeYTDPaymentsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEmployeeYTDPaymentsBackButtonMouseClicked(evt);
            }
        });

        viewEmployeeYTDPaymentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee Name:", "YTD:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewEmployeeYTDPaymentsTable);

        viewEmployeeYTDPaymentsEmployeeNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewEmployeeYTDPaymentsEmployeeNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeeYTDPaymentsEmployeeNameLabel.setText("Employee Name:");

        viewEmployeeYTDPaymentsYTDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewEmployeeYTDPaymentsYTDLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeeYTDPaymentsYTDLabel.setText("YTD:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewEmployeeYTDPaymentsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(viewEmployeeYTDPaymentsEmployeeNameLabel)
                        .addGap(240, 240, 240)
                        .addComponent(viewEmployeeYTDPaymentsYTDLabel)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(viewEmployeeYTDPaymentsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEmployeeYTDPaymentsEmployeeNameLabel)
                    .addComponent(viewEmployeeYTDPaymentsYTDLabel))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewEmployeeYTDPaymentsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeYTDPaymentsBackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        AdminDashBoardFrame adminDashBoardpage = new AdminDashBoardFrame(user, connection);
        adminDashBoardpage.setVisible(true);
    }//GEN-LAST:event_viewEmployeeYTDPaymentsBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployeeYTDPaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployeeYTDPaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployeeYTDPaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewEmployeeYTDPaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewEmployeeYTDPaymentsFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewEmployeeYTDPaymentsBackButton;
    private javax.swing.JLabel viewEmployeeYTDPaymentsEmployeeNameLabel;
    private javax.swing.JTable viewEmployeeYTDPaymentsTable;
    private javax.swing.JLabel viewEmployeeYTDPaymentsYTDLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        fillTable();
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
