/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;

/**
 *
 * @author ryansmac
 */
public class ViewCompanyFiananceLogsFrame extends javax.swing.JFrame {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form ViewCompanyFiananceLogsFrame
     */
    public ViewCompanyFiananceLogsFrame(User user, Connection connection) {
        this.connection = connection;
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewCompanyFinanceLogsBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewCompanyFinanceLogsTable = new javax.swing.JTable();
        viewCompanyFinanceLogsDateAndTimeLabel = new javax.swing.JLabel();
        viewCompanyFinanceLogsAmountLabel = new javax.swing.JLabel();
        viewCompanyFinanceLogsAdminResponsibleLabel = new javax.swing.JLabel();
        viewCompanyFinanceLogsWithdrawalOrDepositLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        viewCompanyFinanceLogsBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsBackButton.setText("Back");
        viewCompanyFinanceLogsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewCompanyFinanceLogsBackButtonMouseClicked(evt);
            }
        });

        viewCompanyFinanceLogsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date/Time of Transaction", "Account Conducting Transaction", "Amount", "Withdrawal/Deposit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewCompanyFinanceLogsTable);

        viewCompanyFinanceLogsDateAndTimeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsDateAndTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewCompanyFinanceLogsDateAndTimeLabel.setText("Date/Time:");

        viewCompanyFinanceLogsAmountLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewCompanyFinanceLogsAmountLabel.setText("Amount:");

        viewCompanyFinanceLogsAdminResponsibleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsAdminResponsibleLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewCompanyFinanceLogsAdminResponsibleLabel.setText("Admin Responsible:");

        viewCompanyFinanceLogsWithdrawalOrDepositLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsWithdrawalOrDepositLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewCompanyFinanceLogsWithdrawalOrDepositLabel.setText("Withdrawal/Deposit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewCompanyFinanceLogsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(viewCompanyFinanceLogsDateAndTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewCompanyFinanceLogsAdminResponsibleLabel)
                .addGap(89, 89, 89)
                .addComponent(viewCompanyFinanceLogsAmountLabel)
                .addGap(94, 94, 94)
                .addComponent(viewCompanyFinanceLogsWithdrawalOrDepositLabel)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(viewCompanyFinanceLogsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCompanyFinanceLogsAmountLabel)
                    .addComponent(viewCompanyFinanceLogsDateAndTimeLabel)
                    .addComponent(viewCompanyFinanceLogsAdminResponsibleLabel)
                    .addComponent(viewCompanyFinanceLogsWithdrawalOrDepositLabel))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCompanyFinanceLogsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCompanyFinanceLogsBackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        AdminDashBoardFrame adminDashBoardpage = new AdminDashBoardFrame(user, connection);
        adminDashBoardpage.setVisible(true);
    }//GEN-LAST:event_viewCompanyFinanceLogsBackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewCompanyFiananceLogsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewCompanyFiananceLogsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewCompanyFiananceLogsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewCompanyFiananceLogsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewCompanyFiananceLogsFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel viewCompanyFinanceLogsAdminResponsibleLabel;
    private javax.swing.JLabel viewCompanyFinanceLogsAmountLabel;
    private javax.swing.JButton viewCompanyFinanceLogsBackButton;
    private javax.swing.JLabel viewCompanyFinanceLogsDateAndTimeLabel;
    private javax.swing.JTable viewCompanyFinanceLogsTable;
    private javax.swing.JLabel viewCompanyFinanceLogsWithdrawalOrDepositLabel;
    // End of variables declaration//GEN-END:variables
}
