/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.*;

/**
 *
 * @author ryansmac
 */
public class ViewAndPayoutEmployeeTimeCardsFrame extends javax.swing.JFrame implements WindowListener {
    private Connection connection;
    private User user;
    
    /**
     * Creates new form ViewAndPayoutEmployeeTimeCardsFrame
     */
    public ViewAndPayoutEmployeeTimeCardsFrame(User user, Connection connection) {
        this.connection = connection;
        this.user = user;
        initComponents();
    }
    
    private void fillTable() {
        try {
            System.out.println("HELLO");
            String psQuery = 
                    "SELECT employeeid, paydate, payamount, hours FROM employee_stubs " +
                    "WHERE approval != 1";
            
            PreparedStatement ps = connection.prepareStatement(psQuery);
            
            System.out.println("Employee ID: " + user.getEmployeeID());
            
//            ps.setInt(1, user.getEmployeeID());
            
            ResultSet stubs = ps.executeQuery();
            System.out.println("GOOD");
            for (int i = 0; stubs.next(); i++) {
                viewAndPayoutEmployeeTimeCardsTable.setValueAt(stubs.getString("employeeid"), i, 1);
                viewAndPayoutEmployeeTimeCardsTable.setValueAt(stubs.getString("paydate"), i, 2);
                viewAndPayoutEmployeeTimeCardsTable.setValueAt(stubs.getString("hours"), i, 3);
                viewAndPayoutEmployeeTimeCardsTable.setValueAt(new String("$" + stubs.getFloat("payamount")), i, 4);                
            }
        }
        catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
     * this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        addWindowListener(this);
        
        jPanel1 = new javax.swing.JPanel();
        viewAndPayoutEmployeeTimeCardsBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewAndPayoutEmployeeTimeCardsTable = new javax.swing.JTable();
        viewCompanyFinanceLogsAdminResponsibleLabel = new javax.swing.JLabel();
        viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel = new javax.swing.JLabel();
        viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu = new javax.swing.JComboBox<>();
        viewAndPayoutEmployeeTimeCardsPayEmployeeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        viewAndPayoutEmployeeTimeCardsBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewAndPayoutEmployeeTimeCardsBackButton.setText("Back");
        viewAndPayoutEmployeeTimeCardsBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAndPayoutEmployeeTimeCardsBackButtonMouseClicked(evt);
            }
        });

        viewAndPayoutEmployeeTimeCardsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Pay Period", "Hours", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewAndPayoutEmployeeTimeCardsTable);

        viewCompanyFinanceLogsAdminResponsibleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewCompanyFinanceLogsAdminResponsibleLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewCompanyFinanceLogsAdminResponsibleLabel.setText("Admin Responsible:");

        viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel.setText("Select Employee To Pay:");

        viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee..." }));

        viewAndPayoutEmployeeTimeCardsPayEmployeeButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewAndPayoutEmployeeTimeCardsPayEmployeeButton.setText("Pay Employee");
        viewAndPayoutEmployeeTimeCardsPayEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAndPayoutEmployeeTimeCardsPayEmployeeButtonMouseClicked(evt);
            }
        });
        
        try {
            String psQuery = 
                    "SELECT employeeid, paydate, payamount FROM employee_stubs " +
                    "WHERE approval != 1";

            PreparedStatement ps = connection.prepareStatement(psQuery);

            ResultSet payInfo = ps.executeQuery();

            for (int i = 0; payInfo.next(); i++) {
                String employee = new String(payInfo.getInt("employeeid") + 
                        ":" + payInfo.getString("paydate") + ":$" + payInfo.getFloat("payamount"));
                
                System.out.println(employee);
                
                viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu.addItem(employee);
            }
        }
        catch (Exception e) {
            System.err.println(e.getMessage());
            
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewAndPayoutEmployeeTimeCardsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(viewAndPayoutEmployeeTimeCardsPayEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewCompanyFinanceLogsAdminResponsibleLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(viewAndPayoutEmployeeTimeCardsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewAndPayoutEmployeeTimeCardsPayEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewCompanyFinanceLogsAdminResponsibleLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAndPayoutEmployeeTimeCardsBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAndPayoutEmployeeTimeCardsBackButtonMouseClicked
        this.remove(this);
        this.setVisible(false);
        AdminDashBoardFrame adminDashBoardpage = new AdminDashBoardFrame(user, connection);
        adminDashBoardpage.setVisible(true);
    }//GEN-LAST:event_viewAndPayoutEmployeeTimeCardsBackButtonMouseClicked

    private void viewAndPayoutEmployeeTimeCardsPayEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAndPayoutEmployeeTimeCardsPayEmployeeButtonMouseClicked
//        try {
//            System.out.println("TRYING TO PAY EMPLOYEE");
//            String psUpdateQuery = 
//                    "UPDATE employees SET " +
//                    "ytd_earned = ytd_earned + ? " +
//                    "WHERE employeeid = ?";
//            
//            String payStub = viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu.getSelectedItem().toString();
//            System.out.println(payStub);
//            String[] payData = payStub.split(":");
//            
//            int employeeID = Integer.parseInt(payData[0]);
//            String payDate = payData[1];
//            float payAmount = Float.parseFloat(payData[2].substring(1));
//            
//            System.out.println("PAYING...");
//            System.out.println("employeeid: " + employeeID);
//            System.out.println("paydate: " + payDate);
//            System.out.println("payamount: " + payAmount);
//            
//            PreparedStatement ps = connection.prepareStatement(psUpdateQuery);
//            
//            ps.setFloat(1, payAmount);
//            ps.setInt(2, employeeID);
//            
//            ps.executeUpdate();
//            
//            psUpdateQuery = 
//                    "UPDATE employee_stubs SET " +
//                    "approval = 1 " +
//                    "WHERE employeeid = ? AND paydate = ?";
//            
//            ps = connection.prepareStatement(psUpdateQuery);
//            
//            ps.setInt(1, employeeID);
//            ps.setString(2, payDate);
//            
//            ps.executeUpdate();
//        }
//        catch (Exception e) {
//            System.err.println(e.getMessage());
//        }
        
        this.remove(this);
        this.setVisible(false);
        ConfirmPayEmployeeFrame confirmPayEmployeePage = new ConfirmPayEmployeeFrame(user, connection);
        confirmPayEmployeePage.setVisible(true);
    }//GEN-LAST:event_viewAndPayoutEmployeeTimeCardsPayEmployeeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewAndPayoutEmployeeTimeCardsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewAndPayoutEmployeeTimeCardsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewAndPayoutEmployeeTimeCardsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewAndPayoutEmployeeTimeCardsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewAndPayoutEmployeeTimeCardsFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewAndPayoutEmployeeTimeCardsBackButton;
    private javax.swing.JButton viewAndPayoutEmployeeTimeCardsPayEmployeeButton;
    private javax.swing.JLabel viewAndPayoutEmployeeTimeCardsSelectEmployeeLabel;
    private javax.swing.JComboBox<String> viewAndPayoutEmployeeTimeCardsSelectEmployeeMenu;
    private javax.swing.JTable viewAndPayoutEmployeeTimeCardsTable;
    private javax.swing.JLabel viewCompanyFinanceLogsAdminResponsibleLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        fillTable();
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
